# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_number:
  bedroom_time_present:
    name: Bedroom Time min
    min: 0
    max: 300
    step: 1
    mode: box
    unit_of_measurement: s

  bedroom_rssi_present:
    name: Bedroom RSSI min
    min: -120
    max: -20
    step: 1
    mode: box
    unit_of_measurement: dBm
  
  plants_rssi_present:
    name: Plants RSSI min
    min: -120
    max: -20
    step: 1
    mode: box
    unit_of_measurement: dBm